### ISSUE TITLE
lua-nginx-module-docset up to date

### ISSUE THREAD

**Issue by tokers** [ruoshan/lua-nginx-module-docset#1]
Hi!

The latest lua-nginx-module version is `v0.10.9`, and the newest docset version in dash is `v0.10.7`, maybe it's time to update. :)

**Comment by ruoshan** [comment]
There you go: https://github.com/Kapeli/Dash-User-Contributions/pull/1441

v0.10.8 is as far as I can go.

**Comment by tokers** [comment]
@ruoshan I am sorry for the incorrect version
